name = "juliaEnvTest3"
uuid = "cc9d6b78-f92d-451c-bc74-59eadb09dff8"
authors = ["Norel <norel.evoagile@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Distributions = "0.25.118"
GLMakie = "0.11.3"
Plots = "1.40.10"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
